### ISSUE TITLE
Things to remember creating the map.xml

### ISSUE THREAD

**Issue by panther2** [DerKuenstler/WWIIDK#6]
- [ ] China has an initital startup according to the rules (the other nations have not), see #4
- [ ] A Factory and an AAGun has to be in every capital, see #4
- [ ] We need capitals (capitol.txt) but we don't need victory cities (territoryAttachment)
- [ ] Think about a (coded) PU-value consider an additional (?) PU value equal to the money to spend in each of the seven arms buildup rounds
- [ ] **or** we can possibly only use the Bid-process 7 times (is to investigate)
- [ ] All units need the attachment "isConstruction" as unitAttachment, to allow them to be placed in territories without factories (I hope it works in sea zones, too) **or** there is an option "unrestricted Placement" that may be fine (is to investigate)
- [x] "Sea Zone" eventualy need to be fixed, see #7
- [ ] ...

**Comment by DerKuenstler** [comment]
All look good except there are seven buildup rounds, not six. (this may not matter to the game) What are the checkboxes for above? Should I be checking them if I agree?

**Comment by panther2** [comment]
Ah ok, I adjusted it to seven rounds, thanks. 

Consider the chekbox-list as Todo-list.
The checkboxes are to be checked, if the respective detail is implemeted (finished).

**Comment by DerKuenstler** [comment]
OK

**Comment by panther2** [comment]
This issue will be reopened if the project is going to be continued.
